#include "utils.h"

const char* const luminary_strings_shading_mode[LUMINARY_SHADING_MODE_COUNT] = {
  [LUMINARY_SHADING_MODE_DEFAULT]        = "None",
  [LUMINARY_SHADING_MODE_ALBEDO]         = "Albedo",
  [LUMINARY_SHADING_MODE_DEPTH]          = "Depth",
  [LUMINARY_SHADING_MODE_NORMAL]         = "Normal",
  [LUMINARY_SHADING_MODE_IDENTIFICATION] = "Identification",
  [LUMINARY_SHADING_MODE_LIGHTS]         = "Lights",
};

const char* const luminary_strings_adaptive_sampling_output_mode[LUMINARY_ADAPTIVE_SAMPLING_OUTPUT_MODE_COUNT] = {
  [LUMINARY_ADAPTIVE_SAMPLING_OUTPUT_MODE_BEAUTY]              = "Beauty",
  [LUMINARY_ADAPTIVE_SAMPLING_OUTPUT_MODE_ERROR]               = "Relative Standard Error (RSE)",
  [LUMINARY_ADAPTIVE_SAMPLING_OUTPUT_MODE_SAMPLE_DISTRIBUTION] = "Sample Distribution",
};

const char* const luminary_strings_tonemap[LUMINARY_TONEMAP_COUNT] = {
  [LUMINARY_TONEMAP_NONE]       = "None",
  [LUMINARY_TONEMAP_ACES]       = "ACES",
  [LUMINARY_TONEMAP_REINHARD]   = "Reinhard",
  [LUMINARY_TONEMAP_UNCHARTED2] = "Uncharted 2",
  [LUMINARY_TONEMAP_AGX]        = "Agx",
  [LUMINARY_TONEMAP_AGX_PUNCHY] = "Agx Punchy",
  [LUMINARY_TONEMAP_AGX_CUSTOM] = "Agx Custom",
};

const char* const luminary_strings_aperture[LUMINARY_APERTURE_COUNT] = {
  [LUMINARY_APERTURE_ROUND]  = "Round",
  [LUMINARY_APERTURE_BLADED] = "Bladed",
};

const char* const luminary_strings_jerlov_water_type[LUMINARY_JERLOV_WATER_TYPE_COUNT] = {
  [LUMINARY_JERLOV_WATER_TYPE_I] = "I",   [LUMINARY_JERLOV_WATER_TYPE_IA] = "IA",   [LUMINARY_JERLOV_WATER_TYPE_IB] = "IB",
  [LUMINARY_JERLOV_WATER_TYPE_II] = "II", [LUMINARY_JERLOV_WATER_TYPE_III] = "III", [LUMINARY_JERLOV_WATER_TYPE_1C] = "1C",
  [LUMINARY_JERLOV_WATER_TYPE_3C] = "3C", [LUMINARY_JERLOV_WATER_TYPE_5C] = "5C",   [LUMINARY_JERLOV_WATER_TYPE_7C] = "7C",
  [LUMINARY_JERLOV_WATER_TYPE_9C] = "9C",
};

const char* const luminary_strings_sky_mode[LUMINARY_SKY_MODE_COUNT] = {
  [LUMINARY_SKY_MODE_DEFAULT]        = "Default",
  [LUMINARY_SKY_MODE_HDRI]           = "HDRI",
  [LUMINARY_SKY_MODE_CONSTANT_COLOR] = "Constant Color",
};

const char* const luminary_strings_material_base_substrate[LUMINARY_MATERIAL_BASE_SUBSTRATE_COUNT] = {
  [LUMINARY_MATERIAL_BASE_SUBSTRATE_OPAQUE]      = "Opaque",
  [LUMINARY_MATERIAL_BASE_SUBSTRATE_TRANSLUCENT] = "Translucent",
};

const char* const luminary_strings_lens_template[LUMINARY_LENS_TEMPLATE_COUNT] = {
  [LUMINARY_LENS_TEMPLATE_THIN_LENS] = "Thin Lens",   [LUMINARY_LENS_TEMPLATE_PHYSICAL_A] = "Physical A",
  [LUMINARY_LENS_TEMPLATE_PHYSICAL_B] = "Physical B", [LUMINARY_LENS_TEMPLATE_PHYSICAL_C] = "Physical C",
  [LUMINARY_LENS_TEMPLATE_PHYSICAL_D] = "Physical D", [LUMINARY_LENS_TEMPLATE_PHYSICAL_E] = "Physical E",
  [LUMINARY_LENS_TEMPLATE_PHYSICAL_F] = "Physical F",
};

const char* const luminary_strings_error_kind[LUMINARY_ERROR_KIND_COUNT] = {
  [LUMINARY_ERROR_NONE]                 = "LUMINARY_ERROR_NONE",
  [LUMINARY_ERROR_UNKNOWN]              = "LUMINARY_ERROR_UNKNOWN",
  [LUMINARY_ERROR_ARGUMENT_NULL]        = "LUMINARY_ERROR_ARGUMENT_NULL",
  [LUMINARY_ERROR_NOT_IMPLEMENTED]      = "LUMINARY_ERROR_NOT_IMPLEMENTED",
  [LUMINARY_ERROR_INVALID_API_ARGUMENT] = "LUMINARY_ERROR_INVALID_API_ARGUMENT",
  [LUMINARY_ERROR_MEMORY_LEAK]          = "LUMINARY_ERROR_MEMORY_LEAK",
  [LUMINARY_ERROR_OUT_OF_MEMORY]        = "LUMINARY_ERROR_OUT_OF_MEMORY",
  [LUMINARY_ERROR_C_STD]                = "LUMINARY_ERROR_C_STD",
  [LUMINARY_ERROR_API_EXCEPTION]        = "LUMINARY_ERROR_API_EXCEPTION",
  [LUMINARY_ERROR_CUDA]                 = "LUMINARY_ERROR_CUDA",
  [LUMINARY_ERROR_OPTIX]                = "LUMINARY_ERROR_OPTIX",
  [LUMINARY_ERROR_PREVIOUS_ERROR]       = "LUMINARY_ERROR_PREVIOUS_ERROR",
  [LUMINARY_ERROR_DEBUG_ASSERT]         = "LUMINARY_ERROR_DEBUG_ASSERT",
  [LUMINARY_ERROR_MISSING_DATA]         = "LUMINARY_ERROR_MISSING_DATA",
  [LUMINARY_ERROR_INVALID_DEVICE]       = "LUMINARY_ERROR_INVALID_DEVICE",
};
