#include "lum_builtins.h"

#include "lum_tokenizer.h"

const char* lum_builtin_types_strings[LUM_BUILTIN_TYPE_COUNT] = {
  [LUM_BUILTIN_TYPE_RGBF] = "RGBF",         [LUM_BUILTIN_TYPE_VEC3] = "vec3",
  [LUM_BUILTIN_TYPE_UINT16] = "uint16_t",   [LUM_BUILTIN_TYPE_UINT32] = "uint32_t",
  [LUM_BUILTIN_TYPE_BOOL] = "bool",         [LUM_BUILTIN_TYPE_FLOAT] = "float",
  [LUM_BUILTIN_TYPE_ENUM] = "Enum",         [LUM_BUILTIN_TYPE_SETTINGS] = "Settings",
  [LUM_BUILTIN_TYPE_CAMERA] = "Camera",     [LUM_BUILTIN_TYPE_OCEAN] = "Ocean",
  [LUM_BUILTIN_TYPE_SKY] = "Sky",           [LUM_BUILTIN_TYPE_CLOUD] = "Cloud",
  [LUM_BUILTIN_TYPE_FOG] = "Fog",           [LUM_BUILTIN_TYPE_PARTICLES] = "Particles",
  [LUM_BUILTIN_TYPE_MATERIAL] = "Material", [LUM_BUILTIN_TYPE_INSTANCE] = "Instance",
  [LUM_BUILTIN_TYPE_METADATA] = "MetaData", [LUM_BUILTIN_TYPE_STRING] = "String"};

const size_t lum_builtin_types_sizes[LUM_BUILTIN_TYPE_COUNT] = {
  [LUM_BUILTIN_TYPE_RGBF]      = sizeof(LuminaryRGBF),
  [LUM_BUILTIN_TYPE_VEC3]      = sizeof(LuminaryVec3),
  [LUM_BUILTIN_TYPE_UINT16]    = sizeof(uint16_t),
  [LUM_BUILTIN_TYPE_UINT32]    = sizeof(uint32_t),
  [LUM_BUILTIN_TYPE_BOOL]      = sizeof(bool),
  [LUM_BUILTIN_TYPE_FLOAT]     = sizeof(float),
  [LUM_BUILTIN_TYPE_ENUM]      = sizeof(uint32_t),
  [LUM_BUILTIN_TYPE_SETTINGS]  = sizeof(LuminaryRendererSettings),
  [LUM_BUILTIN_TYPE_CAMERA]    = sizeof(LuminaryCamera),
  [LUM_BUILTIN_TYPE_OCEAN]     = sizeof(LuminaryOcean),
  [LUM_BUILTIN_TYPE_SKY]       = sizeof(LuminarySky),
  [LUM_BUILTIN_TYPE_CLOUD]     = sizeof(LuminaryCloud),
  [LUM_BUILTIN_TYPE_FOG]       = sizeof(LuminaryFog),
  [LUM_BUILTIN_TYPE_PARTICLES] = sizeof(LuminaryParticles),
  [LUM_BUILTIN_TYPE_MATERIAL]  = sizeof(LuminaryMaterial),
  [LUM_BUILTIN_TYPE_INSTANCE]  = sizeof(LuminaryInstance),
  [LUM_BUILTIN_TYPE_METADATA]  = 0,  // Static
  [LUM_BUILTIN_TYPE_STRING]    = LUM_LITERAL_STRING_MAX_LENGTH};

#define __BUILTIN_ENUM_PAIR(__internal_macro_enum) {.string = #__internal_macro_enum, .value = __internal_macro_enum}

const LumBuiltinEnumValuePair lum_builtin_enums[] = {
  // LuminaryShadingMode
  __BUILTIN_ENUM_PAIR(LUMINARY_SHADING_MODE_DEFAULT), __BUILTIN_ENUM_PAIR(LUMINARY_SHADING_MODE_ALBEDO),
  __BUILTIN_ENUM_PAIR(LUMINARY_SHADING_MODE_DEPTH), __BUILTIN_ENUM_PAIR(LUMINARY_SHADING_MODE_NORMAL),
  __BUILTIN_ENUM_PAIR(LUMINARY_SHADING_MODE_IDENTIFICATION), __BUILTIN_ENUM_PAIR(LUMINARY_SHADING_MODE_LIGHTS),
  // LuminaryFilter
  __BUILTIN_ENUM_PAIR(LUMINARY_FILTER_NONE), __BUILTIN_ENUM_PAIR(LUMINARY_FILTER_GRAY), __BUILTIN_ENUM_PAIR(LUMINARY_FILTER_SEPIA),
  __BUILTIN_ENUM_PAIR(LUMINARY_FILTER_GAMEBOY), __BUILTIN_ENUM_PAIR(LUMINARY_FILTER_2BITGRAY), __BUILTIN_ENUM_PAIR(LUMINARY_FILTER_CRT),
  __BUILTIN_ENUM_PAIR(LUMINARY_FILTER_BLACKWHITE),
  // LuminaryTonemap
  __BUILTIN_ENUM_PAIR(LUMINARY_TONEMAP_NONE), __BUILTIN_ENUM_PAIR(LUMINARY_TONEMAP_ACES), __BUILTIN_ENUM_PAIR(LUMINARY_TONEMAP_REINHARD),
  __BUILTIN_ENUM_PAIR(LUMINARY_TONEMAP_UNCHARTED2), __BUILTIN_ENUM_PAIR(LUMINARY_TONEMAP_AGX),
  __BUILTIN_ENUM_PAIR(LUMINARY_TONEMAP_AGX_PUNCHY), __BUILTIN_ENUM_PAIR(LUMINARY_TONEMAP_AGX_CUSTOM),
  // LuminaryAperture
  __BUILTIN_ENUM_PAIR(LUMINARY_APERTURE_ROUND), __BUILTIN_ENUM_PAIR(LUMINARY_APERTURE_BLADED),
  // LuminaryJerlovWaterType
  __BUILTIN_ENUM_PAIR(LUMINARY_JERLOV_WATER_TYPE_I), __BUILTIN_ENUM_PAIR(LUMINARY_JERLOV_WATER_TYPE_IA),
  __BUILTIN_ENUM_PAIR(LUMINARY_JERLOV_WATER_TYPE_IB), __BUILTIN_ENUM_PAIR(LUMINARY_JERLOV_WATER_TYPE_II),
  __BUILTIN_ENUM_PAIR(LUMINARY_JERLOV_WATER_TYPE_III), __BUILTIN_ENUM_PAIR(LUMINARY_JERLOV_WATER_TYPE_1C),
  __BUILTIN_ENUM_PAIR(LUMINARY_JERLOV_WATER_TYPE_3C), __BUILTIN_ENUM_PAIR(LUMINARY_JERLOV_WATER_TYPE_5C),
  __BUILTIN_ENUM_PAIR(LUMINARY_JERLOV_WATER_TYPE_7C), __BUILTIN_ENUM_PAIR(LUMINARY_JERLOV_WATER_TYPE_9C),
  // LuminarySkyMode
  __BUILTIN_ENUM_PAIR(LUMINARY_SKY_MODE_DEFAULT), __BUILTIN_ENUM_PAIR(LUMINARY_SKY_MODE_HDRI),
  __BUILTIN_ENUM_PAIR(LUMINARY_SKY_MODE_CONSTANT_COLOR),
  // LuminaryMaterialBaseSubstrate
  __BUILTIN_ENUM_PAIR(LUMINARY_MATERIAL_BASE_SUBSTRATE_OPAQUE), __BUILTIN_ENUM_PAIR(LUMINARY_MATERIAL_BASE_SUBSTRATE_TRANSLUCENT)};
LUM_STATIC_SIZE_ASSERT(lum_builtin_enums, sizeof(LumBuiltinEnumValuePair) * LUM_BUILTIN_ENUM_COUNT);
