name: clang-format

on:
  push:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clang-format
        run: clang-format --dry-run --Werror -style=file -i Luminary/lib/UI/*.c Luminary/lib/UI/*.h Luminary/lib/cuda/*.cuh